      SUBROUTINE CONIC (XM,B) 
C     TO OBTAIN MACH NUMRER DERIVATIVES IN RADIAL FLOW
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON /GG/ GAM,GM,G1,G2,G3,G4,G5,G6,G7,G8,G9,GA,RGA,QT
      DATA ONE/1.D+0/,TWO/2.D+0/,THR/3.D+0/,FOUR/4.D+0/
      DIMENSION B(4)
      XMM=XM*XM
      XMM1=XMM-ONE
      XMM2=XMM1**2
      BMM=ONE+G8*XMM
      AREA=(G6+G5*XMM)**GA/XM
      B(1)=AREA**QT
      B(2)=XM*BMM/QT/XMM1/B(1)
      C2=TWO-(ONE+THR*G8)/QT
      C4=G8/QT-ONE
      CMM=XMM*(C2+XMM*C4)-ONE-ONE/QT
      B(3)=B(2)*CMM/XMM2/B(1)
      DMM=(FOUR*C4*XMM+TWO*C2)/CMM-FOUR/XMM1
      B(4)=B(3)*(B(3)/B(2)+XM*B(2)*DMM-ONE/B(1))
      RETURN
      END