      FUNCTION FMV (PMA)
C     TO OBTAIN MACH NUMBER FROM PRANDTL MEYER ANGLE
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON /GG/ GAM,GM,G1,G2,G3,G4,G5,G6,G7,G8,G9,GA,RGA,QT
      ONE=1.D+0
      THIRD=ONE/3.D+0
      VM=(DASIN(ONE)*(PMA/(G2-ONE))**2)**THIRD
      Z=ONE+.895D+0*((G7*(G2-ONE))**2)**THIRD*DTAN(VM)
      DO 1 I=1,100
      ZBET=DSQRT(Z*Z-ONE)
      ANG=G2*DATAN(ZBET/G2)-DATAN(ZBET)
      REM=(ANG-PMA)*Z*(Z*Z+G9)/G9/ZBET
      IF (DABS(REM) .LT. 1.D-10) GO TO 2
1     Z=Z-REM
2     FMV=Z-REM
      RETURN
      END