      SUBROUTINE HEAT
C     DUMMY TO BE MODIFIED FOR SPECIAL CALCULATIONS OF HEAT TRANSFER
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON /HTTR/ HAIR,TAW,TWQ,TWT,TWAT,QFUN,QFUNW,IPQ,IJ,IV,IW
      QFUNW=QFUN
      RETURN
      END