      SUBROUTINE PLATE
C     DUMMY TO BE MODIFIED FOR SPECIAL CALCULATIONS FOR FLEXIBLE PLATE
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON /JACK/ SJ(30),XJ(30),YJ(30),AJ(30)
      RETURN
      END