      FUNCTION TORIC (WIP,SE)
C     TO OBTAIN THROAT RADIUS OF CURVATURE FROM VELOCITY GRADIENT
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON /FG/ GC,GD,GE,GF,GH,GI,HA,HB,HC,HE
      COMMON /GG/ GAM,GM,G1,G2,G3,G4,G5,G6,G7,G8,G9,GA,RGA,QT
      DATA ONE/1.D+0/,THR/3.D+0/,FIV/5.D+0/
      IE=ONE/QT-ONE
      FW=WIP*SE*DSQRT(QT*(GAM+ONE))
      TRR=FW*(ONE+(GC+(THR*GC**2-GD)*FW**2)*FW**2)
1     TR2=TRR**2
      TK=(ONE-G7*(ONE+(GE+GF*TR2)*TR2)*TR2**2/(45.D+0+3*IE))**QT
      FF=FW/TK-TRR*(ONE-TR2*(GC-GD*TR2))
      FP=ONE-TR2*(THR*GC-FIV*GD*TR2)
      TRR=TRR+FF/FP
      IF (DABS(FF) .GT. 1.D-1) GO TO 1
      TORIC=ONE/TRR**2
      RETURN
      END